name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Create NuGet folder
      run: mkdir nuget

    - name: Dotnet restore
      run: dotnet tool restore

    - name: Build Firestore Storage
      run: dotnet run --project build
      working-directory: ./src/IdentityServer4.Firestore.Storage/
      
    - name: Build Firestore
      run: dotnet run --project build
      working-directory: ./src/IdentityServer4.Firestore/

    - name: Replace NuGet.config token
      run: cat .github/NuGet.config | sed -e "s#GITHUB_KEY#${{ secrets.GITHUB_TOKEN }}#" > NuGet.config

    - name: Publish GitHub
      run: dotnet nuget push -s GitHub nuget/**/*.nupkg